# -*- coding: utf-8 -*-
"""PROJECTSPOTIFY.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCBfL6BwjKQs3eptwBfhDh2r5mHdyMCD
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("zaheenhamidani/ultimate-spotify-tracks-db")

print("Path to dataset files:", path)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

df = pd.read_csv(path + "/SpotifyFeatures.csv")

df.head()

df.shape

df.columns

df.info()

df.describe()

df.isnull().sum()

df = df.dropna()

features = df[['danceability','energy','tempo','loudness','valence']]

features.shape

scaler = StandardScaler()

scaled_features = scaler.fit_transform(features)

scaled_df = pd.DataFrame(scaled_features, columns=features.columns)

scaled_df.head()

inertia = []

for k in range(1,10):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_df)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(1,10), inertia, marker='o')
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")
plt.title("Elbow Method for Optimal K")
plt.show()

kmeans = KMeans(n_clusters=5, random_state=42)

df['cluster'] = kmeans.fit_predict(scaled_df)

df['cluster'].value_counts()

cluster_summary = df.groupby('cluster')[features.columns].mean()

print(cluster_summary)

pca = PCA(n_components=2)

pca_result = pca.fit_transform(scaled_df)

pca_df = pd.DataFrame(pca_result, columns=['PC1','PC2'])

pca_df['cluster'] = df['cluster']

plt.figure(figsize=(8,6))

sns.scatterplot(
    x='PC1',
    y='PC2',
    hue='cluster',
    palette='Set1',
    data=pca_df
)

plt.title("Spotify Song Clusters (PCA)")
plt.show()

tsne = TSNE(n_components=2, random_state=42)

tsne_result = tsne.fit_transform(scaled_df.sample(5000))

tsne_df = pd.DataFrame(tsne_result, columns=['TSNE1','TSNE2'])

tsne_df['cluster'] = df['cluster'].sample(5000).values

plt.figure(figsize=(8,6))

sns.scatterplot(
    x='TSNE1',
    y='TSNE2',
    hue='cluster',
    palette='tab10',
    data=tsne_df
)

plt.title("t-SNE Visualization of Spotify Clusters")
plt.show()

